#
name: CDK Business Apps CI
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  ci-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: deploy/cdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: pnpm/action-setup@v4
        with:
          version: "10"
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.1
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run audit
        run: pnpm audit:check
      - name: Run build
        run: pnpm build
#